name: hugo_firebase_demo
on:
    push:
      branches:
        - main

jobs:
    build:
        name: build hugo projects
        runs-on: ubuntu-latest
        steps:
            - name: Checkout Repo
              uses: actions/checkout@v1
              with:
                submodules: true
            - name: Setup Hugo
              uses: peaceiris/actions-hugo@v2
              with:
                hugo-version: 'latest'
            - name: build hugo pages
              run: |
                hugo 
            - name: Archive Production Artifact
              uses: actions/upload-artifact@master
              with:
                name: docs
                path: docs
    deploy:
        name: Deploy
        needs: build
        runs-on: ubuntu-latest
        steps:
            - name: Checkout Repo
              uses: actions/checkout@master
            - name: Download Artifact
              uses: actions/download-artifact@master
              with:
                name: docs
            - name: Deploy to Firebase
              uses: w9jds/firebase-action@v2.2.2
              with:
                args: deploy
              env:
                FIREBASE_TOKEN: ${{ secrets.FIREBASE_TOKEN }}
                PROJECT_ID: homepage-b776f
